images:
- location: "https://dl.rockylinux.org/pub/rocky/9.1/images/x86_64/Rocky-9-GenericCloud-Base-9.1-20230215.0.x86_64.qcow2"
  arch: "x86_64"
  digest: "sha256:53850338cd7e918052e13fc0a34b8383675ac747e168f640cfb7f483e65eac65"
- location: "https://dl.rockylinux.org/pub/rocky/9.1/images/aarch64/Rocky-9-GenericCloud-Base-9.1-20230215.0.aarch64.qcow2"
  arch: "aarch64"
  digest: "sha256:6991592f3308376d63c5a69b353586cee1d67077f1af6d0a3f12126b11a13829"

mountType: "virtiofs"

mounts:
- location: "~"
- location: "/tmp/lima"
  writable: true

vmType: "vz"

rosetta:
  # Enable Rosetta for Linux.
  # Hint: try `softwareupdate --install-rosetta` if Lima gets stuck at `Installing rosetta...`
  enabled: true
  # Register rosetta to /proc/sys/fs/binfmt_misc
  binfmt: true

provision:
- mode: system
  # Run necessary upgrades
  script: |
    #!/bin/bash
    yum -y update && yum -y upgrade
- mode: system
  # This script defines the host.docker.internal hostname when hostResolver is disabled.
  # It is also needed for lima 0.8.2 and earlier, which does not support hostResolver.hosts.
  # Names defined in /etc/hosts inside the VM are not resolved inside containers when
  # using the hostResolver; use hostResolver.hosts instead (requires lima 0.8.3 or later).
  script: |
    #!/bin/sh
    sed -i 's/host.lima.internal.*/host.lima.internal host.docker.internal/' /etc/hosts
- mode: system
  # Uninstall old docker packages
  script: |
    #!/bin/bash
    yum remove -y docker \
        docker-client \
        docker-client-latest \
        docker-common \
        docker-latest \
        docker-latest-logrotate \
        docker-logrotate \
        docker-engine
- mode: system
  # Install docker-ce packages
  script: |
    #!/bin/bash
    yum install -y yum-utils
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    yum install -y docker-ce \
        docker-ce-cli \
        containerd.io \
        docker-buildx-plugin \
        docker-compose-plugin
- mode: system
  # Create docker daemon config
  script: |
    #!/bin/bash
    cat <<EOF > /etc/docker/daemon.json
    {
      "bip": "192.168.64.1/24",
      "mtu": 1400,
      "network-control-plane-mtu": 1400,
      "default-address-pools": [{"base": "192.168.64.0/18", "size": 24}]
    }
    EOF
- mode: system
  # Setup docker service overrides
  script: |
    #!/bin/bash
    mkdir /etc/systemd/system/docker.service.d
    cat <<EOF > /etc/systemd/system/docker.service.d/override.conf
    [Service]
    ExecStart=
    ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H fd:// --containerd=/run/containerd/containerd.sock
    EOF
- mode: system
  # Start and enable docker
  script: |
    #!/bin/bash
    systemctl daemon-reload && \
      systemctl start docker && \
      systemctl enable docker

hostResolver:
  # hostResolver.hosts requires lima 0.8.3 or later. Names defined here will also
  # resolve inside containers, and not just inside the VM itself.
  hosts:
    host.docker.internal: host.lima.internal

portForwards:
- guestPort: 2376
  hostIP: "127.0.0.1"
  hostPort: 62376
