---

docker_old_packages:
  - docker
  - docker-client-latest
  - docker-client
  - docker-common
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate
  - docker-selinux
  - docker-engine-selinux
  - docker-engine

docker_yum_packages:
  - yum-utils
  - device-mapper-persistent-data
  - lvm2

docker_repo_url: "https://download.docker.com/linux/centos/docker-ce.repo"

docker_ver: 17.09.0
docker_rpm: "docker-ce-{{ docker_ver }}.ce"
