---

- name: install yum packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ docker_yum_packages }}"

- name: copy repo file
  get_url:
    remote_src: true
    url: "{{ docker_repo_url }}"
    dest: /etc/yum.repos.d
    owner: root
    group: root
    mode: 0644

- name: "install {{ docker_rpm }}"
  yum:
    name: "{{ docker_rpm }}"
    state: present
  notify: "start_docker_c{{ ansible_distribution_major_version }}"
