---

- name: uninstall older docker packages
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ docker_old_packages }}"
  listen: uninstall_old_packages

- name: start docker - Centos6
  service:
    name: docker
    state: started
    enabled: yes
  listen: start_docker_c6

- name: start docker - Centos7
  systemd:
    name: docker
    state: started
    enabled: yes
  listen: start_docker_c7
